# Generated by Django 3.1.3 on 2020-11-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Загаловок')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Картинка')),
                ('menu', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Логотип')),
                ('image1', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Нижний логотип')),
                ('insta', models.CharField(blank=True, max_length=100, verbose_name='Название соц сети 1')),
                ('insta2', models.CharField(blank=True, max_length=100, verbose_name='Название соц сети 2')),
                ('insta3', models.CharField(blank=True, max_length=100, verbose_name='Название соц сети 3')),
                ('slug', models.URLField(blank=True, verbose_name='Ссылка на соц сети 1')),
                ('slug2', models.URLField(blank=True, verbose_name='Ссылка на соц сети 2')),
                ('slug3', models.URLField(blank=True, verbose_name='Ссылка на соц сети 3')),
                ('footer', models.TextField(max_length=600, verbose_name='Описание нижнего части сайта')),
            ],
            options={
                'verbose_name': 'Редатировать сайт',
                'verbose_name_plural': 'Редатирование сайта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Загаловок')),
                ('title', models.TextField(max_length=350, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Картинка')),
                ('sale', models.CharField(max_length=100, verbose_name='Текст на кнопке')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('available', models.BooleanField(default=True, verbose_name='Отключить товар')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Загаловок')),
                ('title', models.TextField(max_length=350, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Картинка')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('available', models.BooleanField(default=True, verbose_name='Отключить товар')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'index_together': {('id', 'slug')},
            },
        ),
    ]
