# Generated by Django 3.1.3 on 2020-11-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Загаловок')),
                ('title', models.TextField(max_length=350, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('available', models.BooleanField(default=True, verbose_name='Отключить товар')),
                ('categore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textproduct', to='app.category')),
            ],
            options={
                'verbose_name': 'Текстовый товар',
                'verbose_name_plural': 'Текстовые товары',
                'index_together': {('id', 'slug')},
            },
        ),
    ]
