# Generated by Django 3.1.3 on 2020-11-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_textproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textproduct',
            old_name='categore',
            new_name='category',
        ),
    ]
