# Generated by Django 3.1.3 on 2020-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201121_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
