# Generated by Django 3.1.3 on 2020-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201121_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Отключить товар'),
        ),
    ]
