# Generated by Django 3.1.3 on 2020-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201121_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отключить товар'),
        ),
    ]
