# Generated by Django 3.1.3 on 2020-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201121_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='textproduct',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True, verbose_name='Ссылка'),
        ),
    ]
