# Generated by Django 3.1.3 on 2020-11-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_music_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='music',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
