# Generated by Django 3.1.3 on 2020-11-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201123_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textproduct',
            options={'verbose_name': 'Текстовое меню', 'verbose_name_plural': 'Текстовое меню'},
        ),
    ]
